Feat/currency rates hook
eq-lab/slender-ui pull request #43
Opened 2023-09-07 13:27 UTC by baikov98

2023-09-07 13:46 UTC, bouvens requested changes

2023-09-07 13:46 UTC, bouvens commented on packages/app/src/entities/currency-rates/api/currency-rates.ts
> +    const result = await fetch('https://api.coinbase.com/v2/exchange-rates?currency=USD').then(
Let's do not mix `await` and `then` on one string.

It's also a good approach to extract `fetch` with its helper logic to a sort of `getRequest` function.

We already have `postData` in the landing project. We can rename it to `postRequest` and extract as well. This part is not needed right now.

2023-09-07 13:46 UTC, bouvens commented on packages/app/src/entities/currency-rates/context/provider.tsx
> +  }, [])
We have to clear interval on unmount.

```suggestion
  useEffect(() => {
    getRates()
    const intervalId = setInterval(() => {
      getRates()
    }, UPDATE_RATES_INTERVAL_MS)
    return () => {
      clearInterval(intervalId)
    }
  }, [])
```

2023-09-07 15:27 UTC, baikov98 commented on packages/app/src/entities/currency-rates/context/provider.tsx
> +    setInterval(() => {
added

2023-09-07 15:27 UTC, baikov98 commented on packages/app/src/entities/currency-rates/context/provider.tsx
> +  }, [])
added

2023-09-08 05:26 UTC, bouvens commented on packages/app/src/entities/currency-rates/api/currency-rates.ts
> +    const result = await fetch('https://api.coinbase.com/v2/exchange-rates?currency=USD').then(
Thank you

2023-09-08 05:27 UTC, bouvens approved these changes

2023-09-08 05:27 UTC, merged